# fly.toml app configuration file generated for vadymtest on 2023-10-11T22:00:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vadymtest"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
